title: Email Charter
description: An&nbsp;<em>adapted</em>&nbsp;version of the Email Charter created in response to widespread acknowledgement that email is getting out of hand for many people. The original started as a&nbsp;<a href="http://web.archive.org/web/20150315012653/http://tedchris.posthaven.com/help-create-an-email-charter">blog post</a>&nbsp;by TED Curator Chris Anderson and TED Scribe Jane Wulf. Some contributors to the original Charter are listed&nbsp;<a href="http://web.archive.org/web/20150315012653/http://emailcharter.org/comments.html">here</a>.<br>
<h3>Feel free to&nbsp;<a href="https://email-charter.github.io/#add-to-email-signature">add the Email Charter to your email signature</a>.</h3>
logo: /icons/internet-mail.png
theme: jekyll-theme-minimal
github:
  is_user_page: false
google_analytics: "UA-119326789-3"
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
url: "https://email-charter.github.io"
