title: Email Charter
description: An *adapted* version of the Email Charter created in response to widespread acknowledgement that email is getting out of hand for many people. The original  started as a [blog post](http://web.archive.org/web/20150315012653/http://tedchris.posthaven.com/help-create-an-email-charter) by TED Curator Chris Anderson and TED Scribe Jane Wulf. Some contributors to the original Charter are listed [here](http://web.archive.org/web/20150315012653/http://emailcharter.org/comments.html).
logo: /icons/internet-mail.png
theme: jekyll-theme-minimal
github:
  is_user_page: false
google_analytics: "UA-119326789-3"
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
url: "https://email-charter.github.io"
