title: Email Charter
description: <p>10 Tips to avoid email overload | An <em>adapted</em> version of the Email Charter created in response to widespread acknowledgement that email is getting out of hand for many people.</p>
logo: /icons/internet-mail.png
theme: jekyll-theme-minimal
github:
  is_user_page: false
google_analytics: "UA-119326789-3"
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
url: "https://email-charter.github.io"
